import { Builtin } from '../values';

export var stringMethods: Map<string, Builtin> = new Map([
  // ["capitalize", new Builtin("capitalize", string_capitalize)],
  // ["codepoint_ords", new Builtin("codepoint_ords", string_iterable)],
  // ["codepoints", new Builtin("codepoints", string_iterable)],
  // ["count", new Builtin("count", string_count)],
  // ["elem_ords", new Builtin("elem_ords", string_iterable)],
  // ["elems", new Builtin("elems", string_iterable)],
  // ["endswith", new Builtin("endswith", string_startswith)],
  // ["find", new Builtin("find", string_find)],
  // ["format", new Builtin("format", string_format)],
  // ["index", new Builtin("index", string_index)],
  // ["isalnum", new Builtin("isalnum", string_isalnum)],
  // ["isalpha", new Builtin("isalpha", string_isalpha)],
  // ["isdigit", new Builtin("isdigit", string_isdigit)],
  // ["islower", new Builtin("islower", string_islower)],
  // ["isspace", new Builtin("isspace", string_isspace)],
  // ["istitle", new Builtin("istitle", string_istitle)],
  // ["isupper", new Builtin("isupper", string_isupper)],
  // ["join", new Builtin("join", string_join)],
  // ["lower", new Builtin("lower", string_lower)],
  // ["lstrip", new Builtin("lstrip", string_strip)],
  // ["partition", new Builtin("partition", string_partition)],
  // ["removeprefix", new Builtin("removeprefix", string_removefix)],
  // ["removesuffix", new Builtin("removesuffix", string_removefix)],
  // ["replace", new Builtin("replace", string_replace)],
  // ["rfind", new Builtin("rfind", string_rfind)],
  // ["rindex", new Builtin("rindex", string_rindex)],
  // ["rpartition", new Builtin("rpartition", string_partition)],
  // ["rsplit", new Builtin("rsplit", string_split)],
  // ["rstrip", new Builtin("rstrip", string_strip)],
  // ["split", new Builtin("split", string_split)],
  // ["splitlines", new Builtin("splitlines", string_splitlines)],
  // ["startswith", new Builtin("startswith", string_startswith)],
  // ["strip", new Builtin("strip", string_strip)],
  // ["title", new Builtin("title", string_title)],
  // ["upper", new Builtin("upper", string_upper)],
]);
